machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t nesurion/cookbook:latest .

deployment:
  hub:
    branch: master
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push nesurion/cookbook:latest

