version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application container
     - run: docker build -t nesurion/cookbook:latest .

     # deploy the container
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker push nesurion/cookbook:latest
